# Generated by Django 4.1.3 on 2024-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='Age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='BMI',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='BloodPressure',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='DiabetesPedigreeFunction',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='Glucose',
            field=models.IntegerField(default=0.5),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='Insulin',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='Pregnancies',
            field=models.IntegerField(default=0.5),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='SkinThickness',
            field=models.FloatField(default=0.5),
        ),
    ]
